name: 自动打包Electron安装包
on:
  push:
    branches:
      - release-pack  # 只有这个分支推送才打包

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: 安装Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: 安装依赖
        run: npm ci
      - name: 打包exe
        run: npm run dist
      - name: 上传安装包
        uses: actions/upload-artifact@v4
        with:
          name: windows-setup
          path: dist/*.exe